### ISSUE TITLE
Incompatible with io_grpc_grpc_java 0.21.0 or newer

### ISSUE THREAD

**Issue by zegl** [stackb/rules_proto#103]
[This commit](https://github.com/grpc/grpc-java/commit/745aa0a2f570d74e7d7fe0c72334c24e21b8ab17#diff-87f75ce3f908a819a9a2c77ffeffcc38) shipped in v0.21.0 made `@io_grpc_grpc_java//compiler:grpc_java_plugin` private, causing breakage in `rules_proto`.

Bazel will error-out with the following trace:

```
ERROR: /private/var/tmp/_bazel_xyz/2b76f1f79d664c3181ce1190fe27bebe/external/build_stack_rules_proto/java/BUILD.bazel:10:1:
in proto_plugin rule @build_stack_rules_proto//java:grpc_java:
target '@io_grpc_grpc_java//compiler:grpc_java_plugin' is not visible from target '@build_stack_rules_proto//java:grpc_java'.
Check the visibility declaration of the former target if you think the dependency is legitimate
```

**Comment by pcj** [comment]
Hmm.  That's somewhat annoying it's now private.  Probably we can use the `buildozer_http_archive` rule to load `io_grpc_grpc_java` and rewrite that visibility to public again until a better solution is found.

**Comment by skeptic-monkey** [comment]
can't we use the protoc-gen-grpc-java artifact from maven instead ?
https://mvnrepository.com/artifact/io.grpc/protoc-gen-grpc-java

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
