### ISSUE TITLE
dart make_dart_context not found 

### ISSUE THREAD

**Issue by mishudark** [stackb/rules_proto#107]
Bazel version: 0.28.0

Error:
```
io_bazel_rules_dart/dart/build_rules/internal/dart_vm_snapshot.bzl:1:1: file ':common.bzl' does not contain symbol 'make_dart_context
```

**Comment by aaliddell** [comment]
The upstream [rules_dart](https://github.com/dart-archive/rules_dart) repo has been archived, so is now in an unmaintained state. Some forks exist, but are generally also unmaintained on a frequent basis. The best I can find is https://github.com/cbracken/rules_dart

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
