### ISSUE TITLE
Issue with latest version of grpc

### ISSUE THREAD

**Issue by nlopezgi** [stackb/rules_proto#108]
Hi,
I'm having problems updating my pin in rules_k8s to com_github_grpc_grpc due to an issue with this repo on which rules_k8s also depends on.
After updating to latest version of grpc (https://github.com/bazelbuild/rules_k8s/pull/384) my builds are failing with the following error:
`(19:18:24) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/build_stack_rules_proto/cpp/BUILD.bazel:12:1: no such target '@com_github_grpc_grpc//:grpc_cpp_plugin': target 'grpc_cpp_plugin' not declared in package '' defined by /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_github_grpc_grpc/BUILD and referenced by '@build_stack_rules_proto//cpp:grpc_cpp'`
Full error trace: https://buildkite.com/bazel/rules-k8s-k8s/builds/1879#5aaacfdf-f2f5-4c8e-a749-a2efe82bad4c
thanks!

**Comment by aaliddell** [comment]
The compiler plugin targets [have moved](https://github.com/grpc/grpc/commit/bd5ed4fddd7e3aa9121a9eed92b820ef37e03b48) in the current master of gRPC, but this commit has not reached a public release cut yet.

**Comment by nlopezgi** [comment]
Thanks for the quick response. We can wait until the next gRPC public release then.

**Comment by Calvin-cn** [comment]
Just have met the same situation in the latest released version https://github.com/grpc/grpc/releases/tag/v1.25.0, please process https://github.com/stackb/rules_proto/pull/133 to fix it.

**Comment by gertvdijk** [comment]
#133 was merged, but then reverted in #140 (reasoning absent).

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
