### ISSUE TITLE
ruby_grpc_compile tries to generate services for well known proto

### ISSUE THREAD

**Issue by rsinghumasscs** [stackb/rules_proto#109]
Hi,
I have a proto file containing gRPC service definition which references the google.protobuf.Timestamp proto. 

I have following bazel target:
```
ruby_grpc_compile(
    name = "x_ruby_grpc_compile",
    visibility = ["//visibility:private"],
    deps = [":x_proto"],
    verbose = 4,
)
```

Target x_proto is generated like so

```
proto_library(
    name = "x_proto",
    srcs = ["x.proto"],
    visibility = ["//visibility:public"],
    deps = ["@com_google_protobuf//:timestamp_proto"],
)
```

From the verbose output I see that it is expecting ```bazel-out/darwin-fastbuild/bin/external/com_google_protobuf/google/protobuf/timestamp_services_pb.rb``` to be created as well and fails saying ```output 'external/com_google_protobuf/google/protobuf/timestamp_services_pb.rb' was not created```. How to prevent it from expecting this ```timestamp_services_pb.rb```?

Link to repo with reproducible code https://github.com/rsinghumasscs/stackb_ruby_grpc_compile_repro

Thanks a lot!

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
