### ISSUE TITLE
Remove trailing whitespaces with a linter?

### ISSUE THREAD

**Issue by qzmfranklin** [stackb/rules_proto#11]
Hi,

I am trying to hack around this repository.

One frustrating fact is the proliferation of trailing whtiespaces.

The trailing whitespaces are so ubiquitous that I find it impossible to modify the existing code without incurring meaningless whitespace-only changes.

I and motivated (out of personal hacking interest) and would like to send a PR that trims the trailing whitespaces and add a linter for it if the owners are willing to commit to the no-trailing-whtiespace style.

Thanks,
Zhongming

**Comment by pcj** [comment]
Thanks for you interest!  Can you provide an example of the trailing whitespace?

**Comment by qzmfranklin** [comment]
Here are a few screenshots.

The red blocks are trailing whitespaces (tabs and spaces alike).


![1](https://user-images.githubusercontent.com/5695733/50132722-779a7400-02c3-11e9-9f4a-7cec7908c265.png)
![2](https://user-images.githubusercontent.com/5695733/50132763-a9133f80-02c3-11e9-9834-b48c960f2027.png)
![3](https://user-images.githubusercontent.com/5695733/50132734-85e89000-02c3-11e9-9e92-92886d92b8d5.png)

**Comment by qzmfranklin** [comment]
Hi @pcj 

I created a PR (https://github.com/stackb/rules_proto/pull/12) to address this issue.

That PR does two things:
1. Remove ALL trailing whitespaces in this repository.
2. Enable a workflow that auto-trims trailing whitespaces with pre-commit hooks.

Currently the TravisCI build fails with an error message that seems irrelevant to my PR. Need some help there.

Thanks and all,
Zhongming

**Comment by laurentlb** [comment]
I recommend using [Buildifier](https://github.com/bazelbuild/buildtools) for fixing the formatting.

**Comment by pcj** [comment]
Closed in #12
