### ISSUE TITLE
Missing Assembly Reference error with csharp_grpc_library

### ISSUE THREAD

**Issue by plule** [stackb/rules_proto#110]
Hello,

When building a  `csharp_grpc_library`, I get the error:
> error CS0234: The type or namespace name 'BindServiceMethodAttribute'
does not exist in the namespace 'Grpc.Core' (are you missing an assembly reference?)

`BindServiceMethodAttribute` seems to be part of the `Grpc.Core.Api` assembly which is not included in `csharp/nuget/nuget.bzl`. It might be an issue with the script generating this file.

Here is a repository to reproduce the issue:
[Repository](https://github.com/plule/stackb_rules_proto_reproduction)
`bazel build //:missing_assembly_reference`

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
