### ISSUE TITLE
csharp_grpc_library: Missing output when building a GRPC .proto importing a message-only .proto

### ISSUE THREAD

**Issue by plule** [stackb/rules_proto#111]
Hello,

Using the csharp_* rules, if I have a proto file **with** a service importing a proto file **without** a service, then I cannot build a GRPC library out of the first one. The error is:

>ERROR: ...: output 'missing_output_pb/WithoutServiceGrpc.cs' was not created
ERROR: ...: not all outputs were created or valid

`csharp_grpc_library` declares all its dependencies with `csharp_grpc_compile`, leading to this issue.

The only workaround I found is to create empty services in the .proto files. What would be the proper way to do that?

[Repository to reproduce the issue](https://github.com/plule/stackb_rules_proto_reproduction)
`bazel build //:missing_output`

Thanks!

**Comment by rsinghumasscs** [comment]
@plule I am having the same issue for ruby_grpc_compile (https://github.com/stackb/rules_proto/issues/109) except in my case the proto I am referring to is a well-know proto (google/protobuf/Timestamp.proto) so I can't even add a dummy service :(.

**Comment by plule** [comment]
@rsinghumasscs Well now that you say it, I can depend on well-known proto without issue in C#, even though they are message-only proto libraries

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
