### ISSUE TITLE
Building with python_grpc_library leads to conflicting actions: Same python wrapper generated twice

### ISSUE THREAD

**Issue by dave-xnor** [stackb/rules_proto#113]
MCVE is in this other repo over here: https://github.com/dave-xnor/bazel-py-rule-issue

I have three proto definition files - one has a grpc service defined, it depends on the other two.  Each of the three has a `proto_library` rule; two also have a `python_proto_library` rule and the third (with the service) has a `python_grpc_library` rule.  

Building the targets independently works: `bazel query //... | xargs -n 1 bazel build`.

Building them together fails with a conflicting action report, apparently due to one of the python protobuf wrappers of the non-service protobufs being generated twice: `bazel build //src/proto:all`.

(In the real repository I boiled down to get this MCVE the file reported as the conflicting action varied on each run - though it was always one of the non-service-defining protos.)

This could be a problem with `rules_proto`, or something underlying in Bazel, or in grpc, or, very possibly, in my understanding of how these rules are supposed to be used to build something.  (In which case the "fix" isn't in code, it's in documentation. IMO. Because I do read the docs, and even look at examples.)

```prose
ERROR: file 'src/proto/b_pb2.py' is generated by these conflicting actions:
Label: //src/proto:b_proto
RuleClass: proto_library rule
Configuration: de2b1250788dfeca9c7ec0dbeba85f06
Mnemonic: ProtoCompile
Action key: 7e9a1878eff3415c62f50f7e698db12d, 53d25eb3e1a7c9d9533bc6d2d132d176
Progress message: ProtoCompile src/proto/b_pb2.py
PrimaryInput: File:[/home/dbakin/src/bazel-py-rule-issue[source]]src/proto/a.proto
PrimaryOutput: File:[[<execution_root>]bazel-out/k8-fastbuild/bin]src/proto/b_pb2.py
Primary outputs are different: 1971704056, 2050816446
Owner information: []#@build_stack_rules_proto//python:python_grpc_compile.bzl%python_grpc_compile_aspect[verbose_string="1"] BuildConfigurationValue.Key[de2b1250788dfeca9c7ec0dbeba85f06] //src/proto:b_proto BuildConfigurationValue.Key[de2b1250788dfeca9c7ec0dbeba85f06] false {verbose_string=[1]}, []#@build_stack_rules_proto//python:python_proto_compile.bzl%python_proto_compile_aspect[verbose_string="1"] BuildConfigurationValue.Key[de2b1250788dfeca9c7ec0dbeba85f06] //src/proto:b_proto BuildConfigurationValue.Key[de2b1250788dfeca9c7ec0dbeba85f06] false {verbose_string=[1]}
MandatoryInputs: Attempted action contains artifacts not in previous action (first 5): 
	external/com_github_grpc_grpc/grpc_python_plugin
Outputs: Attempted action contains artifacts not in previous action (first 5): 
	src/proto/b_pb2.py
	src/proto/b_pb2_grpc.py
Previous action contains artifacts not in attempted action (first 5): 
	src/proto/b_pb2.py
ERROR: com.google.devtools.build.lib.actions.MutableActionGraph$ActionConflictException: for src/proto/b_pb2.py, previous action: action 'ProtoCompile src/proto/b_pb2.py', attempted action: action 'ProtoCompile src/proto/b_pb2.py'
INFO: Elapsed time: 6.556s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (13 packages loaded, 1848 targets configured)
```

**Comment by meastham** [comment]
Has anybody found a workaround for this? Or is there an upstream bug to track?

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
