### ISSUE TITLE
cpp_grpc_library --incompatible_depset_is_not_iterable=false

### ISSUE THREAD

**Issue by vasilynikita** [stackb/rules_proto#114]
building cpp_grpc_library failed with this error.

ERROR: /private/var/tmp/_bazel_vasily/aec80661cf884ca8f9b0c1d9e70344a0/external/com_github_grpc_grpc/src/proto/grpc/reflection/v1alpha/BUILD:21:1: in _generate_cc rule @com_github_grpc_grpc//src/proto/grpc/reflection/v1alpha:_reflection_proto_codegen: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_vasily/aec80661cf884ca8f9b0c1d9e70344a0/external/com_github_grpc_grpc/src/proto/grpc/reflection/v1alpha/BUILD", line 21
		_generate_cc(name = '_reflection_proto_codegen')
	File "/private/var/tmp/_bazel_vasily/aec80661cf884ca8f9b0c1d9e70344a0/external/com_github_grpc_grpc/bazel/generate_cc.bzl", line 10, in generate_cc_impl
		[f for src in ctx.attr.srcs for f in src.proto.transitive_imports]
type 'depset' is not iterable. Use the `to_list()` method to get a list. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.

The source https://github.com/grpc/grpc/blob/master/bazel/generate_cc.bzl#L48, seemed already fixed with the .to_list(). Updating the com_github_grpc_grpc to the latest probably will fix this error.

**Comment by pcj** [comment]
Closing stale PRs and issues, please reopen new one if desired.
