### ISSUE TITLE
Relation with https://github.com/rules-proto-grpc/rules_proto_grpc?

### ISSUE THREAD

**Issue by qzmfranklin** [stackb/rules_proto#116]
What's the relationship of this repo with https://github.com/rules-proto-grpc/rules_proto_grpc?

`rules_proto_grpc` contains a lot of code originally written in this repo (git commit credits are preserved). But it's not a fork.

**Comment by pcj** [comment]
Closing stale PRs and issues, please reopen new one if desired.
