### ISSUE TITLE
Rule gateway_grpc_library dependencies.

### ISSUE THREAD

**Issue by malekbs** [stackb/rules_proto#122]
The definition of gateway_grpc_library  [here](https://github.com/stackb/rules_proto/blob/master/github.com/grpc-ecosystem/grpc-gateway/gateway_grpc_library.bzl)  is very troublesome. 

Specifically, in lines 22 and 23.  

Other than the syntax:
```
 proto = deps[0],
```

When a proto files depends on other proto files, this can be problematic :  in the same way it passes  
```
 deps = ["@go_googleapis//google/api:annotations_go_proto"],
```
It should pass the other go library of the proto dependencies.

Thanks,

**Comment by FrancoisChastel** [comment]
+1

**Comment by FrancoisChastel** [comment]
After some investigation, I don't see any obvious solution except : not having import except the http.annotion.proto, there is more complexity involved than just putting this.

I am considering to migrate our codebase to gRPC-Web.

**Comment by malekbs** [comment]
> +1, in my case it created an unexpected behavior ! I have couple of dependencies for a `grpc_gateway` and when using it in my codebase I had a non-existent ServiceHandler.
> Now I know why.... it was looking for ServiceHandler from the first proto definition....
> 
> So how to manage when we have multiple dependencies ? (when a given proto import another one from the a brother package for example)

A possible workaround consists: 
- Generate  gateway library  for proto1. 
- Create a rule that passes the deps & extend to annotations_go_proto or do it by hands using go_proto_library. 

This works for me. 

cheers,

**Comment by FrancoisChastel** [comment]
Cheers thank you ! If this solution work it could be an actual fix !

**Comment by malekbs** [comment]
> Cheers thank you ! If this solution work it could be an actual fix !

Well, It is a fix.  
Keep in mind though that this way will not ensure backward compatibility.

**Comment by pcj** [comment]
Closing stale PRs and issues, please reopen new one if desired.
