### ISSUE TITLE
rules_proto quoting bug on Windows

### ISSUE THREAD

**Issue by mehrdadn** [stackb/rules_proto#129]
Hi, [this line](https://github.com/stackb/rules_proto/blob/3ca0bf4156d189d38f5b049c2c5de891191fda4f/aspect.bzl#L298) is buggy:

    command = " ".join([protoc.path] + args)

Unfortunately quoting is not so simple, because of [this line](https://github.com/stackb/rules_proto/blob/3ca0bf4156d189d38f5b049c2c5de891191fda4f/aspect.bzl#L277):

    pathsep = ctx.configuration.host_path_separator
    args.append("--descriptor_set_in=%s" % pathsep.join(
        [f.path for f in descriptor_sets.to_list()],
    ))

Unlike on Linux, `pathsep` on Windows is a semicolon, which (unlike a colon) has special meaning to Bash. You end up with something like this on Windows (simplified):

    bash.exe -c "path/to/protoc.exe --descriptor_set_in=file1.proto.bin;file2.proto.bin --python_out=file.proto"

This causes the `;` to be interpreted as a command separator, causing Bash to attempt to execute `file2.proto.bin` as a _shell script_ (!), which causes it to crash and burn quite badly:

    error executing shell command: 'bash.exe -c protoc.exe --descriptor_set_in=file1.proto.bi...' failed (Exit 2)
    Missing input file.
    file2.proto.bin: line 2: $'\216\037': command not found

Escaping rules are [unintuitive and complicated](https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/) on Windows.

However, the good news is that, since the escaping necessary is rather limited here, I think you can solve this easily as follows:

1.  Change

        command = " ".join([protoc.path] + args)  # SAME

    to

        command = '"$@"'

2. Add the following argument to `ctx.actions.run_shell`:

        # This is different!
        arguments = [protoc.path] + args,
        ...

P.S. Note that `path/to/protoc.exe` may also contain spaces (e.g. if the username contains spaces), and I _suspect_ that may be the issue in #128. The problems are different, but both stem from lack of proper quoting, and I think should be resolved by this.

**Comment by pcj** [comment]
Closing stale PRs and issues, please reopen new one if desired.
