### ISSUE TITLE
use a version of grpc/grpc-java which has fix for maven central http issue

### ISSUE THREAD

**Issue by abhishek-pandey** [stackb/rules_proto#138]
https://github.com/stackb/rules_proto/blob/bedc40cd47b43dde857a7720066aadcf76c7dd3b/deps.bzl#L323

the grpc-java version that we rely upon should include commit: https://github.com/grpc/grpc-java/commit/a4299eb6bed3c2f2497f583d0c4620c9f31ec455

**Comment by CelsoSantos** [comment]
This! I need this please... Currently I have to setup a proxy to rewrite the requests from `http://central.maven.org/` to `https://repo.maven.apache.org`

**Comment by karlbateman** [comment]
Assuming this is related to the `Unknown host: central.maven.org` error.

A fix described in [iotaledger/compass/issues/142](https://github.com/iotaledger/compass/issues/142#issuecomment-586735326) worked for me :smile:

**Comment by pcj** [comment]
Closing stale PRs and issues, please reopen new one if desired.
