### ISSUE TITLE
Unable to build examples

### ISSUE THREAD

**Issue by gertvdijk** [stackb/rules_proto#139]
As discussed in the [offending commit](https://github.com/stackb/rules_proto/commit/6b334ece48828fb8e45052976d3516f808819ac7) here on GH, examples fail to build, e.g. this one:

```
$ cd example/node/node_grpc_compile
$ USE_BAZEL_VERSION=1.2.1 bazelisk build --incompatible_no_rule_outputs_param=false //...
```
```
WARNING: Download from https://mirror.bazel.build/github.com/google/protobuf/archive/v3.7.1.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/archive/be3b1fc838386bdbea39d9750ea4411294870575.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: /path/to/bazel/cache/external/build_stack_rules_proto/node/BUILD.bazel:13:1: no such package '@com_github_grpc_grpc//src/compiler': BUILD file not found in directory 'src/compiler' of external repository @com_github_grpc_grpc. Add a BUILD file to a directory to mark it as a package. and referenced by '@build_stack_rules_proto//node:grpc_js'
ERROR: Analysis of target '//:greeter_node_grpc' failed; build aborted: Analysis failed
INFO: Elapsed time: 9.127s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (7 packages loaded, 7 targets configured)
```

If I update grpc to 1.26.0, new problems appear:

    ERROR: /path/to/bazel/cache/external/build_stack_rules_proto/node/BUILD.bazel:13:1: error loading package '@com_github_grpc_grpc//src/compiler': in /path/to/bazel/cache/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl: in /path/to/bazel/cache/external/upb/bazel/upb_proto_library.bzl: Unable to find package for @bazel_version//:bazel_version.bzl: The repository '@bazel_version' could not be resolved. and referenced by '@build_stack_rules_proto//node:grpc_js'
    ERROR: Analysis of target '//:greeter_node_grpc' failed; build aborted: Analysis failed

The level of complexity in the stackb dependency management stopped me from making a PR, also because I don't use much of that part. In my project I've been able to fix this by following grpc's README instructions to load it as a dependency manually, then patching a bit on the rules to adjust for new paths of virtual imports.

**Comment by pcj** [comment]
Definitely not dead, but yes, needs better maintenance.  Guilty as charged.

**Comment by pcj** [comment]
Closing stale PRs and issues, please reopen new one if desired.
