### ISSUE TITLE
Fix Bazel incompatible changes

### ISSUE THREAD

**Issue by laurentlb** [stackb/rules_proto#14]
I'd like to be able to build rules_closure with --all_incompatible_changes:
  `bazel test --all_incompatible_changes //...`

It may not be possible to fix every issue now due to transitive dependencies, but we should try to fix the issues from this repository.

**Comment by laurentlb** [comment]
There are still some issues, for example with these flags:
*  `--incompatible_disallow_filetype`
*  `--incompatible_disable_deprecated_attr_params`
*  `--incompatible_bzl_disallow_load_after_statement`
*  `--incompatible_no_transitive_loads`

cc @pcj

**Comment by pcj** [comment]
WIP branch is aspect_impl.

**Comment by pcj** [comment]
Fixed by #75.  This was pretty challenging.
