### ISSUE TITLE
Plugin usage documentation is incorrect

### ISSUE THREAD

**Issue by CharlesG-Branch** [stackb/rules_proto#145]
Each of these [READMEs](https://github.com/stackb/rules_proto/blob/master/python/README.md#optional-attributes) include optional attributes for passing in plugins, [but this feature doesn't look supported anymore.](https://github.com/stackb/rules_proto/blob/master/aspect.bzl#L26-L30) Looks like this impacts all of the languages.

I was able to get around the issue by creating a new rule based on `python_proto_compile` that includes the new plugin in `python_proto_compile_aspect` — essentially like what `python_grpc_compile` is doing.

What's the proper way to be passing in custom plugins? I can update the documentation once I understand this better.

EDIT: For what it's worth, this is to get mypy-protobuf integrated. https://github.com/dropbox/mypy-protobuf

**Comment by pcj** [comment]
Closing stale PRs and issues, please reopen new one if desired.
