### ISSUE TITLE
Replace `bind()` with `alias()`

### ISSUE THREAD

**Issue by qzmfranklin** [stackb/rules_proto#15]
In Bazel, `bind()` has long been deprecated in favor of `alias()`:
https://github.com/bazelbuild/bazel/issues/1952

This repo still uses quite a few of them, for example:
```
//external:protobuf_clib
//external:protobuf_headers
//external:protocol_compiler
```

Indeed, a `git grep -n 'native\.bind'` would yield a lot more.

I'd like to contribute to this part if  @pcj 'd think this is a good idea.

**Comment by promiseofcake** [comment]
Do you happen to know what version of Bazel introduced `alias` @qzmfranklin?

**Comment by pcj** [comment]
Most / all of the bind usages in this repo mimic those in https://github.com/protocolbuffers/protobuf/blob/master/BUILD and https://github.com/grpc/grpc/blob/master/bazel/grpc_deps.bzl (to satisfy building those libraries).  If there is a technical reason to change to alias, I'm open to it but I don't think we need to change something just to satisfy that issue thread.

**Comment by qzmfranklin** [comment]
@pcj 

Bazel already recommended using `alias` over `bind` (https://docs.bazel.build/versions/master/be/workspace.html#bind). This is not just a style change. There are serious functional considerations as described in https://github.com/bazelbuild/bazel/issues/1952.

Furthermore, the fact that `grpc` or `protobuf` repos are doing something is not a valid argument for other repositories to do that same. Indeed, in this case, `grpc` and `protobuf` should probably have switched to `alias` per the recommendation.

I don't think this is going to make a big difference for this repo either way for the moment. But the usage of `bind` could hamper future development because of its own quirks.
