### ISSUE TITLE
Supporting import prefix in python_proto_library

### ISSUE THREAD

**Issue by bilisun** [stackb/rules_proto#154]
I currently have a proto library (kubernetes_api_proto) depending on another proto library with an import prefix (kubernetes_apimachinery_proto), compiled like:

proto_library(
      name = "kubernetes_api_proto",
      srcs = glob([
          "**/*.proto",
      ]),
      import_prefix = "k8s.io/api",
      visibility = ["//visibility:public"],
      deps = [
          "@com_github_kubernetes_apimachinery//:kubernetes_apimachinery_proto",
      ],
 )

proto_library(
      name = "kubernetes_apimachinery_proto",
      srcs = glob([
          "**/*.proto",
      ]),
      import_prefix = "k8s.io/apimachinery",
      visibility = ["//visibility:public"],
      deps = [],
  )

load("@build_stack_rules_proto//python:python_proto_library.bzl", "python_proto_library")

python_proto_library(
     name = "kubernetes_api_py_proto",
     deps = [
         "kubernetes_api_proto",
     ],
)

I'm using stackb's python_proto_library to generate python code for kubernetes_api_proto, but am running into issues related to the import prefix. 

Specifically, I'm seeing something like this when building `bazel build "@com_github_kubernetes_api//:kubernetes_api_py_proto" -s --verbose_failures`:

(cd /home/bsun/.cache/bazel/_bazel_bsun/f9cd3e8575869b8acf5811ee737b1745/execroot/myproject && \
  exec env - \
  /bin/bash -c 'bazel-out/host/bin/external/protobuf_archive/protoc --descriptor_set_in=bazel-out/k8-fastbuild/bin/external/com_github_kubernetes_apimachinery/kubernetes_apimachinery_proto-descriptor-set.proto.bin --python_out=bazel-out/k8-fastbuild/bin/external/com_github_kubernetes_apimachinery pkg/api/resource/generated.proto pkg/apis/meta/v1/generated.proto pkg/apis/meta/v1beta1/generated.proto pkg/apis/testapigroup/v1/generated.proto pkg/runtime/generated.proto pkg/runtime/schema/generated.proto pkg/util/intstr/generated.proto')

ERROR: /home/bsun/.cache/bazel/_bazel_bsun/f9cd3e8575869b8acf5811ee737b1745/external/com_github_kubernetes_apimachinery/BUILD.bazel:3:1: error executing shell command: '/bin/bash -c bazel-out/host/bin/external/protobuf_archive/protoc --descriptor_set_in=bazel-out/k8-fastbuild/bin/external/com_github_kubernetes_apimachinery/kubernetes_apimachinery_proto-descriptor-...' failed (Exit 1)

pkg/api/resource/generated.proto: No such file or directory

Target @com_github_kubernetes_api//:kubernetes_api_py_proto failed to build

This happens because the import prefix `k8s.io/apimachinery` is not prepended before each of these files in the argument for this command. It seems like the overall issue is that the protos from https://github.com/stackb/rules_proto/blob/master/aspect.bzl#L166 do not take into account the import prefix, and as a result the import prefix is not propagated in https://github.com/stackb/rules_proto/blob/master/aspect.bzl#L294 and https://github.com/stackb/rules_proto/blob/master/aspect.bzl#L244. 

What would the proper way to fix this look like? Thank you!

WORKSPACE file for reference:

http_archive(
     name = "build_stack_rules_proto",
     urls = ["https://github.com/stackb/rules_proto/archive/b2913e6340bcbffb46793045ecac928dcf1b34a5.tar.gz"],
     sha256 = "d456a22a6a8d577499440e8408fc64396486291b570963f7b157f775be11823e",
     strip_prefix = "rules_proto-b2913e6340bcbffb46793045ecac928dcf1b34a5",
)

load("@build_stack_rules_proto//python:deps.bzl", "python_proto_library")

python_proto_library()

load("@io_bazel_rules_python//python:pip.bzl", "pip_import", "pip_repositories")

pip_repositories()

pip_import(
    name = "protobuf_py_deps",
    requirements = "@build_stack_rules_proto//python/requirements:protobuf.txt",
)

load("@protobuf_py_deps//:requirements.bzl", protobuf_pip_install = "pip_install")

protobuf_pip_install()

**Comment by pcj** [comment]
Closing stale PRs and issues, please reopen new one if desired.
