### ISSUE TITLE
reference to external/local_jdk/jre/bin/java in protoc-gen-scala.go can fail

### ISSUE THREAD

**Issue by dsilvasc** [stackb/rules_proto#155]
The protoc-gen-scala.go wrapper expects a file 'external/local_jdk/jre/bin/java' to exist at:
  
 https://github.com/stackb/rules_proto/blob/3ca0bf4156d189d38f5b049c2c5de891191fda4f/scala/protoc-gen-scala.go#L22

This can fail in some environments:

```
2020/06/22 14:40:13 Could not get exit code for failed program: external/local_jdk/jre/bin/java, [-jar bazel-out/host/bin/example-plugin/compiler_plugin_deploy.jar bazel-out/host/bin/example-plugin/protoc-gen-example-plugin_/protoc-gen-example-plugin]
2020/06/22 14:40:13 fork/exec external/local_jdk/jre/bin/java: no such file or directory
--gen-example-plugin_out: protoc-gen-example-plugin: Plugin failed with status code 255.
```

Is it possible for a go binary to look up the java execution runtime with `@bazel_tools//tools/jdk:current_java_runtime` instead?

**Comment by pcj** [comment]
Closing stale PRs and issues, please reopen new one if desired.
