### ISSUE TITLE
FR: kubebuilder controller-gen as protoc-gen-crd from .proto to .yaml crd

### ISSUE THREAD

**Issue by gattytto** [stackb/rules_proto#157]
hello
this is a feature request:
the [controller-gen](https://github.com/kubernetes-sigs/controller-tools/blob/master/cmd/controller-gen/main.go) tool reads annotations from go code but when go code is generated from .proto files, maybe it would be good to have a .proto version that takes annotations and generates the crd's. According to protoc design this could be implemented by protoc-gen-crd plugin? 

I hope this makes sense as I am a newcommer to go, bazel, protbuf and grpc.

**Comment by pcj** [comment]
This is a nice idea but outside the scope of this repository.  If you can build the `protoc-gen-crd` binary you could then use this repo to generate outputs using a custom `proto_plugin` rule.

**Comment by gattytto** [comment]
thank you @pcj I'll try to make an add-on then
