### ISSUE TITLE
question about using protobuf 3.6.1

### ISSUE THREAD

**Issue by cdg720** [stackb/rules_proto#160]
Is there a reason why the README.md uses protobuf 3.6.1? 

https://github.com/stackb/rules_proto/tree/master/python#workspace-2
```
pip_import(
    name = "protobuf_py_deps",
    requirements = "@build_stack_rules_proto//python/requirements:protobuf.txt",
)

load("@protobuf_py_deps//:requirements.bzl", protobuf_pip_install = "pip_install")
``` 
which installs https://github.com/stackb/rules_proto/blob/master/python/requirements/protobuf.txt

**Comment by pcj** [comment]
Closing stale PRs and issues, please reopen new one if desired.
