### ISSUE TITLE
Updating version of com_google_protobuf

### ISSUE THREAD

**Issue by danbosnichill** [stackb/rules_proto#163]
Hi.  I noticed this library is using protobuf-3.7.1 which is pretty old.  What are the timelines for updating to more recent deps?

I found the following repo that uses more recent deps:
https://github.com/rules-proto-grpc/rules_proto_grpc

**Comment by dmadisetti** [comment]
To add to this, the mirror used is now offline: https://mirror.bazel.build/github.com/google/protobuf/archive/v3.7.1.tar.gz

**Comment by pcj** [comment]
Closing stale PRs and issues, please reopen new one if desired.
