### ISSUE TITLE
Failed to resolve com_google_protobuf_javalite

### ISSUE THREAD

**Issue by electricmind007** [stackb/rules_proto#165]
Failed to resolve com_google_protobuf_javalite

We are getting the following error message when resolving the internal dependency com_google_protobuf_javalite of io_grpc_grpc_java. Please fix the issue on priority as it is affecting many users.
 
java.io.IOException: Error downloading [https://github.com/google/protobuf/archive/384989534b2246d413dbcd750744faab2607b516.zip] to /home/jenkins/.cache/bazel/_bazel_jenkins/5179c138f504d5cc88845edd18541adb/external/com_google_protobuf_javalite/384989534b2246d413dbcd750744faab2607b516.zip: GET returned 404 Not Found
ERROR: /home/jenkins/.cache/bazel/_bazel_jenkins/5179c138f504d5cc88845edd18541adb/external/io_grpc_grpc_java/protobuf-lite/BUILD.bazel:1:13: no such package '@com_google_protobuf_javalite//': java.io.IOException: Error downloading [https://github.com/google/protobuf/archive/384989534b2246d413dbcd750744faab2607b516.zip] to /home/jenkins/.cache/bazel/_bazel_jenkins/5179c138f504d5cc88845edd18541adb/external/com_google_protobuf_javalite/384989534b2246d413dbcd750744faab2607b516.zip: GET returned 404 Not Found and referenced by '@io_grpc_grpc_java//protobuf-lite:protobuf-lite'

**Comment by pcj** [comment]
Closing stale PRs and issues, please reopen new one if desired.
