### ISSUE TITLE
Potential name conflicts when depending on external protos

### ISSUE THREAD

**Issue by qzmfranklin** [stackb/rules_proto#17]
Hi,

I have a use case that references `proto_library` targets defined in external repositories .e.g `@io_bazel`.

Here is how to reproduce the issue.

1. Pull in the dependencies of rules_proto for python.

2. Create `tools/cpp/analysis/BUILD` with the following content:
```python
py_proto_library(
    name = 'extra_actions_base_py_proto',
    deps = ['@io_bazel//src/main/protobuf:extra_actions_base_proto'],
)
```

The `py_proto_library` is the one imported from `rules_proto/python`.

The `extra_actions_base_py_proto`  target, when built, yields the file 
```
build/genfiles/tools/cpp/analysis/extra_actions_base_py_proto_pb/src/main/protobuf/extra_actions_base_pb2.py
```

I see two issues:
  - This path is probably too long. This could be argued. I won't touch this in this issue.
  - There is a potential name conflict issue. I will explain more on this.

Looking through the code base of rules_proto, I figured that you really wanted me to import the generated python proto library like the following:
```
from src.main.protobuf import extra_actions_base_pb2
```

The assumption is that the `native.py_library()` target generated by `py_proto_library` automatically adds the `name_pb` to the `includes` field so that the above import works.

However, here is the issue I ran into:

By chance, my repository also has a `src` directory:
```bash
src/
├── algorithm
├── base
├── __configure_deploy__.py
├── deploy_config.yaml
├── protos
├── __pycache__
└── ui
```

The python target I want to create depend on both the aformentioned `py_proto_library` target, as imported as `extra_actions_base_pb2`, and a `py_library` target in the `src/base` directory of my own repository:
```python
py_binary(
    name = 'gen_cmd_py',
    srcs = ['gen_cmd.py'],
    main = 'gen_cmd.py',
    deps = [
        ':extra_actions_base_py_proto',
        '//src/base/python:arg_parse',
        '//src/base/python:util',
    ],
)
```

The `gen_cmd.py` script looks like the following:
```python
from src.main.protobuf import extra_actions_base_pb2
from src.base.python import arg_parse
from src.base.python import util
```

Well, this target builds correctly. But at runtime, it fails with the following error:
```bash
    from src.base.python import arg_parse
ModuleNotFoundError: No module named 'src.base'
```

After digging around, I found that the `PYTHONPATH` (i.e., `sys.path`) has the following directories:
```bash
['/home/zhongming/git/LogiOcean/tools/cpp/analysis',
 '/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/execroot/logi/bazel-out/k8-fastbuild/bin/tools/cpp/analysis/gen_cmd_py.runfiles',
 '/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/execroot/logi/bazel-out/k8-fastbuild/bin/tools/cpp/analysis/gen_cmd_py.runfiles/com_google_protobuf/python',
 '/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/execroot/logi/bazel-out/k8-fastbuild/bin/tools/cpp/analysis/gen_cmd_py.runfiles/logi/tools/cpp/analysis/extra_actions_base_py_proto_pb',
 '/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/execroot/logi/bazel-out/k8-fastbuild/bin/tools/cpp/analysis/gen_cmd_py.runfiles/com_google_protobuf',
 '/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/execroot/logi/bazel-out/k8-fastbuild/bin/tools/cpp/analysis/gen_cmd_py.runfiles/six',
 '/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/execroot/logi/bazel-out/k8-fastbuild/bin/tools/cpp/analysis/gen_cmd_py.runfiles/logi',
 '/usr/lib/python36.zip',
 '/usr/lib/python3.6',
 '/usr/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/dist-packages',
 '/usr/local/lib/python3.6/dist-packages/python_dateutil-2.7.3-py3.6.egg',
 '/usr/local/lib/python3.6/dist-packages/swagger_client-1.0.0-py3.6.egg',
 '/usr/lib/python3/dist-packages']
```

In this list, `/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/execroot/logi/bazel-out/k8-fastbuild/bin/tools/cpp/analysis/gen_cmd_py.runfiles/logi/tools/cpp/analysis/extra_actions_base_py_proto_pb` is what leads to the previously mentioned `ModuleNotFoundError` because it also has a `src` sub-directory:
```bash
├── __init__.py
└── src
    ├── __init__.py
    ├── main
    └── __pycache__
```

I tried removing `imports = [name_pb]` from `python_proto_library.bzl`. But that wouldn't do me any good. Because at that time, my own `src/base` directory would cause the import of the proto library to fail.

Contemplating on this, I believe the source problem lies in the fact that `py_proto_library` copies the `.proto` files over and generates the `_pb2.py` file (and `.pb.cc` and `pb.h` files for `cc_proto_library`) in a different directory than the directory containing the **original** `.proto` file (not the copied one).

As a comparison, the Bazel built-in `cc_proto_library` would generate the `pb.cc` and `pb.h` files in the same directory as the **original** `.proto` file. For example, if the `proto_library` is `@io_bazel//src/main/protobuf:extra_actions_base_proto`, the generated files would be
```bash
# From $(bazel info bazel-genfiles)

# For py_proto_library()
external/io_bazel/src/main/protobuf/extra_actions_base_pb2.py

# For cc_proto_library()
external/io_bazel/src/main/protobuf/extra_actions_base.pb.cc
external/io_bazel/src/main/protobuf/extra_actions_base.pb.h
```

That would allow consumers of the `{lang}_proto_library()` targets to import them in a safe, and sane way:
```python
from external.io_bazel.src.main.protobuf import extra_actions_base_pb2
```
```c++
#include <external/io_bazel/src/main/protobuf/extra_actions_base.pb.h>
```

I'd propose to change the structure of rules_proto to be consistent with this paradigm so that referencing `proto_library` targets defined in external repositories becomes unambiguous.

**Comment by pcj** [comment]
The main issue is that ~skylark~ starlark rules do not allow one to "work" outside the package they are defined in.  So, when you `ctx.action.declare_file`, any file you create must within that package, which has the downstream ramifications you observe.  Without having reviewed the specific implementation of the native rules, I don't think they have this restriction.

Arguably the "best" way to accomplish proto compilation is via an aspect-based implementation (which may solve the aforementioned issue), but doing that in a generic way for multiple languages is not trivial.

In any case, I agree the paths for generated protos can get confusing and problematic.

**Comment by qzmfranklin** [comment]
Hi @pcj:

Thanks for the response! I researched and experimented a little bit more and reached the same point (root cause and solution) you brought up. I am happy that problem is ACK'ed and the root problem is thoroughly exposed. Will work around this issue by copying `.proto` files around for now.

I believe that the Bazel built-in `{cc,java}_proto_library` rules use an aspect-based approach.  This belief came from [this blog post](https://blog.bazel.build/2017/02/27/protocol-buffers.html).  Though that blog post (2017/02/27) was pretty old by now (2018/12/20).

I am very interested in 'doing that (the aspect way) in a generic way for multiple languages is not trivial' you mentioned. I know it could be hard and a little far fetching, but would you like to shed more light on the difficulties that you can envision?

**Comment by pcj** [comment]
OK I have an initial working aspect-based implementation on the "aspect" branch.  It still makes my brain hurt, and the code is in complete chaos but you're welcome to try it out.

It works well for dynamic languages like python but will make rules like cpp_proto_library implementations quite difficult.  

https://github.com/stackb/rules_proto/tree/aspect

**Comment by qzmfranklin** [comment]
Thanks for the response. I won't have time to try it out right at the moment. But I will keep an eye on this and try to get this to work when I get some time.

Thanks for everything. Closing for now.
