### ISSUE TITLE
Feature Request: Support Dart

### ISSUE THREAD

**Issue by mark-dropbear** [stackb/rules_proto#220]
I'm starting to see Dart get used in more and more projects involving multiple languages using gRPC and realized that according to the documentation here https://bazel-contrib.github.io/SIG-rules-authors/proto-grpc.html that it is one of the only languages currently not supported by any Bazel option.

As such I wanted to make a request to see if it could be supported in this particular project? ✌️

Some relevant links:

- https://github.com/grpc/grpc-dart
- https://github.com/google/protobuf.dart
- https://github.com/google/protobuf.dart/tree/master/protoc_plugin

**Comment by pcj** [comment]
Very few people seem to be building dart projects with bazel, as such the feature is not planned at this time.  Happy to review a PR.
