### ISSUE TITLE
Support strip_import_prefix

### ISSUE THREAD

**Issue by alexeagle** [stackb/rules_proto#221]
Related to https://github.com/bazelbuild/bazel-gazelle/issues/1173

This fails

```
# gazelle:proto_strip_import_prefix /rt/proto/libs/libbdican
# gazelle:proto file
# gazelle:go_generate_proto false
# gazelle:proto_plugin py implementation builtin:python
# gazelle:proto_rule proto_compile implementation stackb:rules_proto:proto_compile
# gazelle:proto_rule proto_py_library implementation stackb:rules_proto:proto_py_library
# gazelle:proto_language py plugin py
# gazelle:proto_language py rule proto_compile
# gazelle:proto_language py rule proto_py_library

proto_library(
    name = "GenericParamEnumeration_proto",
    srcs = ["GenericParamEnumeration.proto"],
    strip_import_prefix = "/rt/proto/libs/libbdican",
    visibility = ["//visibility:public"],
)

proto_compile(
    name = "GenericParamEnumeration_py_compile",
    outputs = ["GenericParamEnumeration_pb2.py"],
    plugins = ["@build_stack_rules_proto//plugin/builtin:python"],
    proto = "GenericParamEnumeration_proto",
)
```

Because the protoc command line is

`bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc $@' '' '--python_out=bazel-out/k8-opt/bin' '--descriptor_set_in=bazel-out/k8-opt/bin/rt/proto/libs/libbdican/GenericParamEnumeration_proto-descriptor-set.proto.bin' GenericParamEnumeration.proto`

that means that the file was written to `bazel-out/k8-opt/bin/GenericParamEnumeration_pb2.py` but Bazel expected it in the output directory for the package:

```
ERROR: BUILD.bazel:14: output 'rt/proto/libs/libbdican/GenericParamEnumeration_pb2.py' was not created
```

If I comment out the `strip_import_prefix` line then it works (the pb2.py file is written to the path Bazel expects)

**Comment by alexeagle** [comment]
This seems to be the code which governs the behavior

https://github.com/stackb/rules_proto/blob/master/pkg/protoc/file.go#L216-L219
> stripImportPrefix is removed from the predicted filename
I think this is wrong? The file will be written to the same place as without stripImportPrefix, it just changes how other .proto files will reference this one.

**Comment by alexeagle** [comment]
I see that protoc wants that last argument to be something that appears in the descriptor file. So maybe it's actually the calculation of the `python_out` argument that needs to be adjusted.

**Comment by alexeagle** [comment]
https://github.com/alexeagle/repro_stackb_py_proto_deps/compare/works shows that when the `strip_import_prefix` is removed, then the `deps` are generated correctly.

**Comment by alexeagle** [comment]
one more note, I think if https://github.com/bazelbuild/bazel-gazelle/issues/1173 were resolved, that's probably the principled fix at the right layer, and maybe naturally solves this issue as well.  I think @aptenodytes-forsteri is looking into that.

**Comment by samschlegel** [comment]
Just ran into this as well, but the mentioned https://github.com/bazelbuild/bazel-gazelle/issues/1173 isn't the issue I'm running into. We simply have a top-level `/proto` directory with `# gazelle:proto_strip_import_prefix /proto` configured in `/proto/BUILD`. The proto_library rules are all generated fine and the deps work, but the rules in this repo seem to just not take it into account at all, or do so in a way that also strips the prefix from the generated file path, which leads to 
```
ERROR: /proto/validate/BUILD.bazel:19:14: output 'proto/validate/validate_pb2.py' was not created
ERROR: /proto/validate/BUILD.bazel:19:14: output 'proto/validate/validate_pb2.pyi' was not created
ERROR: /proto/validate/BUILD.bazel:19:14: Compiling protoc outputs for ["validate.proto"] failed: not all outputs were created or valid
```

Looking at the sandbox afterwards, these *were* generated, but they were generated at `validate/validate_pb2.py`, one level up than expected.

**Comment by samschlegel** [comment]
After manually adding `output_mappings` things work as expected. Does support for generating this just need to be added to the builtin python plugin, or is there some configuration that's missing?

**Comment by samschlegel** [comment]
Copying the way the cpp_plugin.go works did get the output_mappings working...but it also highlighted an issue that also shows up in the cpp rules. Adjusting the outputs in the `Configure()` method like so does get the output_mapping generating
```diff
diff --git a/pkg/plugin/builtin/python_plugin.go b/pkg/plugin/builtin/python_plugin.go
index 57b32c4..0cbfb47 100644
--- a/pkg/plugin/builtin/python_plugin.go
+++ b/pkg/plugin/builtin/python_plugin.go
@@ -28,7 +28,7 @@ func (p *PythonPlugin) Configure(ctx *protoc.PluginContext) *protoc.PluginConfig
        flags := parsePythonPluginOptions(p.Name(), ctx.PluginConfig.GetFlags())
 
        pyFiles := protoc.FlatMapFiles(
-               pythonGeneratedFileName(ctx.Rel),
+               pythonGeneratedFileName(ctx.ProtoLibrary.StripImportPrefix(), ctx.Rel),
                protoc.Always,
                ctx.ProtoLibrary.Files()...,
        )
@@ -51,12 +51,16 @@ func (p *PythonPlugin) Configure(ctx *protoc.PluginContext) *protoc.PluginConfig
 // pythonGeneratedFileName is a utility function that returns a function that
 // computes the name of a predicted generated file having the given
 // extension(s) relative to the given dir.
-func pythonGeneratedFileName(reldir string) func(f *protoc.File) []string {
+func pythonGeneratedFileName(stripImportPrefix, reldir string) func(f *protoc.File) []string {
+       prefix := strings.TrimPrefix(stripImportPrefix, "/")
        return func(f *protoc.File) []string {
                name := strings.ReplaceAll(f.Name, "-", "_")
                if reldir != "" {
                        name = path.Join(reldir, name)
                }
+               if strings.HasPrefix(name, prefix) {
+                       name = strings.TrimPrefix(name[len(prefix):], "/")
+               }
                return []string{name + "_pb2.py"}
        }
 }
```

But it also seems to confuse the library srcs and they start generating without the relative directory stripped
```
diff --git a/proto/validate/BUILD.bazel b/proto/validate/BUILD.bazel
index df13e515410..491824d4bd9 100644
--- a/proto/validate/BUILD.bazel
+++ b/proto/validate/BUILD.bazel
@@ -18,7 +18,10 @@ proto_library(
 
 proto_compile(
     name = "validate_python_compile",
+    output_mappings = [
+        "validate_pb2.pyi=validate/validate_pb2.pyi",
+        "validate_pb2.py=validate/validate_pb2.py",
+    ],
     outputs = [
         "validate_pb2.py",
         "validate_pb2.pyi",
@@ -32,7 +35,7 @@ proto_compile(
 
 proto_py_library(
     name = "validate_py_library",
-    srcs = ["validate_pb2.py"],
+    srcs = ["validate/validate_pb2.py"],
     visibility = ["//visibility:public"],
     deps = ["@com_google_protobuf//:protobuf_python"],
 )
 ```
