### ISSUE TITLE
proto_compile rule generator sorts "plugins" lexicographically

### ISSUE THREAD

**Issue by VoIdemar** [stackb/rules_proto#266]
Hello.

`proto_compile` rule generator sorts "plugins" lexicographically (as simple strings) using the [GetPluginLabels](https://github.com/stackb/rules_proto/blob/7c95feba87ae269d09690fcebb18c77d8b8bcf6a/pkg/protoc/plugin_configuration.go#L32) function. Sometimes this causes build errors in cases when there is a dependency between different plugins (one depends on the output of the other or smth like this).

Is there any way to override this behavior? Or... maybe there is a plan to improve the current implementation somehow?

Would really appreciate your answer.

Thanks in advance.

**Comment by pcj** [comment]
Very late reply here, but do you have an example?  Will re-open if still an issue.
