### ISSUE TITLE
Failing to use rules_js/js_binary as a workable tool for proto_plugin

### ISSUE THREAD

**Issue by perezd** [stackb/rules_proto#272]
I'm not sure yet if this is a problem with rules_proto or rules_js, but I've created a reproducer here to see if you can help me debug: https://github.com/perezd/protobuf_es_reproducer

OK, so what seems to be happening here is that the tool target is a shell script that needs to source in runfiles.bash from @bazel_tools, I did a quick workaround to see if I could trick it and failed :(

To exercise the issue, run this:

```
bazel build //:test_es_proto
```

You'll see something like:
```
ERROR: cannot find bazel_tools/tools/bash/runfiles/runfiles.bash
```

Note, that if I run the js_binary target directly, it boots up and runs as expected. This is was made me suspect this could be an issue w/ rules_proto, and I should check here first. Thoughts?

**Comment by pcj** [comment]
Closing since rules_js support has been added.  Please create a new issue if still relevant.
