### ISSUE TITLE
Some deps will not be resolved if run for only a dir

### ISSUE THREAD

**Issue by gou4shi1** [stackb/rules_proto#301]
For example, dirA depends on dirB, after `bazel run //:gazelle -- dirA`, `go_proto` or `proto_cc_library` of `dirB` will not be added into `dirA/BUILD` as deps.
I have to do this `bazel run //:gazelle -- dirA dirB` to solve this problem, but I don't want to update `dirB/BUILD`.

**Comment by pcj** [comment]
Closing due to age.
