### ISSUE TITLE
WorkspaceSnippet is ignored in deps gen

### ISSUE THREAD

**Issue by sacsar** [stackb/rules_proto#307]
The `WorkspaceSnippet` field in `ProtoDependencyInfo` is unused/ignored when the dependency bazel files are generated.

This came up because I'm trying to use aspect-build/rules-ts in my fork, so I expect I'll have a fix sooner or later.

**Comment by sacsar** [comment]
I've dug into this a bit more and see what's missing--this requires templating `WORKSPACE`.

**Comment by pcj** [comment]
@sacsar I'll close this but let's re-open this if still an issue.
