### ISSUE TITLE
Migrate to new rules_js/aspect_rules_ts?

### ISSUE THREAD

**Issue by sacsar** [stackb/rules_proto#308]
Would you be interested in a PR swapping over to the aspect-build/rules_js + aspect_rules_ts?

I have swapped the typescript plugin/rules over in a fork. It needs cleanup (especially around dependencies), but it is usable. I expect swapping the JS plugins/rules wouldn't be too much additional work.

**Comment by mrmeku** [comment]
@sacsar Could you post a link to your fork? I'd love to check it out

**Comment by sacsar** [comment]
@mrmeku https://github.com/Nextdoor/rules_proto/tree/rules_ts -- still in a branch because it still needs some cleanup, but we're using it successfully.

**Comment by mrmeku** [comment]
@paladine I think this is fixed
