### ISSUE TITLE
checksum changed for `rules_proto` and dependencies

### ISSUE THREAD

**Issue by FrancoisChastel** [stackb/rules_proto#310]
Hello there,

following the new changes on GitHub the checksum seemed to have changed for both `rules_proto` and some of the deps.

You can find the news from GitHub here : https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/

Here are the errors that may have already guessed :

```
Error in download_and_extract: java.io.IOException:
Error downloading [https://github.com/stackb/rules_proto/archive/v2.0.1.tar.gz] to /private/var/tmp/_bazel_/08ce9519deea235749151ce4ec120ea0/external/build_stack_rules_proto/temp4327983922892248404/v2.0.1.tar.gz: 
Checksum was 16e9c8bf4774af6483db8b5669d66445b0a320cbb3cf7ef4fd31e5a89a480c1e but wanted ac7e2966a78660e83e1ba84a06db6eda9a7659a841b6a7fd93028cd8757afbfb
```

This should need to be fix on the docs and the `core_deps.bzl` !

Regarding the wide impact it can have there are some discussions already there : https://github.com/orgs/community/discussions/45830

Maybe it could be fixed on your end for the moment ? 

**Edit :**

GitHub will revert so far the changes but maybe it will be worth it to future-proof this part ? 
https://github.com/orgs/community/discussions/45830#discussioncomment-4823799

**Comment by pcj** [comment]
Will revisit if github changes stance.
