### ISSUE TITLE
question: could you pinpoint the protoc version of this repository compared to bazelbuild/rules_proto?

### ISSUE THREAD

**Issue by mrwormhole** [stackb/rules_proto#313]
Hello there,

I was just curious to ask the protoc-gen-grpc-go version of this toolchain and bazelbuild/rules_proto toolchain to increase my understanding? 

~~we are migrating from bazelbuild/rules_proto to stackb/rules_proto but I have started to see `pb.UnimplementedEchoServiceServer` in my Go files more often so I would like to know why this occurs, 2-3 years ago when I used gRPC I didn't had to do this for every struct I have~~

~~but now I did a fresh install of protobuf/grpc without bazel as well and it requires me to add `pb.UnimplementedEchoServiceServer` in the new code, I was wondering if this is protoc version related thing, if you can pinpoint me to the correct direction about version differences of `stackb_rules_proto` and `bazelbuild/rules_proto` I would be so happy~~

**Comment by pcj** [comment]
Generally you can check the version of a bazel dependency by inspecting the output of `bazel query --output build //external:name_of_dependency`, which will produce a stack-trace of how the dependency was loaded.
