### ISSUE TITLE
inconsistent workspace name for grpc-gateway

### ISSUE THREAD

**Issue by qzmfranklin** [stackb/rules_proto#32]
The [grpc-gateway](https://github.com/grpc-ecosystem) repo officially uses `grpc_ecosystem_grpc_gateway` as the Bazel workspace name, as demonstrated [here](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/proto/examplepb/BUILD.bazel).

In `github.com/grpc-ecosystem/grpc-gateway`, the same repo is referenced via a different name `com_github_grpc_ecosystem_grpc_gateway`.

This inconsistency causes build errors for me (and likely other people too).

Admittedly, the name prefixed with `com_github` (i.e., the name rules_proto chose) sounds more correct to me. But I don't think it is easy to convince `grpc-gateway` to change the workspace name just because of this.

What's an acceptable solution here?

**Comment by pcj** [comment]
We should just adopt the name they chose.  Happy to accept a PR or I will fix and close this issue.

**Comment by qzmfranklin** [comment]
Sorry for the late reply. Created a PR to rename the workspace name as discussed.

**Comment by pcj** [comment]
Closed by #39
