### ISSUE TITLE
No such package '@com_github_grpc_grpc//

### ISSUE THREAD

**Issue by jemeador** [stackb/rules_proto#332]
When setting up a minimal project with only the WORKSPACE and BUILD.bazel boilerplate and at least one .proto file using a service, I get the following error:
````
no such package '@com_github_grpc_grpc//': The repository '@com_github_grpc_grpc' could not be resolved: Repository '@com_github_grpc_grpc' is not defined and referenced by '//foo:bar_grpc_cc_library
````
Bazel version: 5.4.0 or 6.2.0
rules_proto version: head of master (3799dab3ead79435332c90b8770ea31a8af14bbc) or 2.1.0

**Comment by pcj** [comment]
This suggests the `@com_github_grpc_grpc` dependency has not been declared in the WORKSPACE.  You can use your own version or `load("@build_stack_rules_proto//deps:grpc_core_deps.bzl", "grpc_core_deps")` and `grpc_core_deps()`.
