### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by Zemnmez** [stackb/rules_proto#356]
I don't think there's anything special about my setup but somehow it gets this error. commit:

https://github.com/zemn-me/monorepo/blob/dd7a4ccea02fdcc3eb0540882ea678ae5cc5adb1/

**Comment by rbtcollins** [comment]
This looks like  a interaction in gazelle itself. We see this

Note that the gazelle version here is substantially newer than the default version grabbed by stackb's rules_proto.

```
fatal error: concurrent map read and map write

goroutine 1 [running]:
github.com/bazelbuild/bazel-gazelle/resolve.(*resolveConfig).findOverride(0xc000146db0, {{0x9e71a7?, 0x9e9411?}, {0xc000392781?, 0xb?}}, {0x9e71a7, 0x2})
        external/gazelle~0.35.0/resolve/config.go:90 +0xeb
github.com/bazelbuild/bazel-gazelle/resolve.FindRuleWithOverride(0x95a1a0?, {{0x9e71a7?, 0xc000392781?}, {0xc000392781?, 0x40?}}, {0x9e71a7, 0x2})
        external/gazelle~0.35.0/resolve/config.go:35 +0xf9
github.com/bazelbuild/bazel-gazelle/language/go.ResolveGo(0xc00045e3c0, 0x411a05?, 0xc0019e8460, {0xc000392781, 0x31}, {{0xc0004981e1, 0xe}, {0xc000482138, 0x16}, {0xc0004a2ed0, ...}, ...})
        external/gazelle~0.35.0/language/go/resolve.go:134 +0x2dd
github.com/bazelbuild/bazel-gazelle/language/go.(*goLang).Resolve.func1({0xc000392781?, 0xc001b6ed38?})
        external/gazelle~0.35.0/language/go/resolve.go:80 +0x8a
github.com/bazelbuild/bazel-gazelle/rule.(*PlatformStrings).Map.func1({0xc000475400, 0xb, 0x2?})
        external/gazelle~0.35.0/rule/platform_strings.go:147 +0xca
github.com/bazelbuild/bazel-gazelle/rule.(*PlatformStrings).MapSlice.func1(...)
        external/gazelle~0.35.0/rule/platform_strings.go:165
github.com/bazelbuild/bazel-gazelle/rule.(*PlatformStrings).MapSlice(0xc001b6f008, 0x7effd3f78108?)
        external/gazelle~0.35.0/rule/platform_strings.go:208 +0xec
github.com/bazelbuild/bazel-gazelle/rule.(*PlatformStrings).Map(0xac5680?, 0xc0003fa3f0?)
        external/gazelle~0.35.0/rule/platform_strings.go:155 +0x6f
github.com/bazelbuild/bazel-gazelle/language/go.(*goLang).Resolve(0x2ae3e90, 0xc00045e3c0, 0xc0001a81e0, 0xc0019e8460, 0xc000490b00, {0x9b00c0?, 0xc0004b3bf0?}, {{0xc0004981e1, 0xe}, {0xc000482138, ...}, ...})
        external/gazelle~0.35.0/language/go/resolve.go:79 +0x26c
main.runFixUpdate({0xc00002e05a, 0x1a}, 0x7ffca8979f71?, {0xc0001a8020, 0x3, 0x3})
        external/gazelle~0.35.0/cmd/gazelle/fix-update.go:471 +0x1bff
main.run({0xc00002e05a?, 0x1a?}, {0xc0001a8010?, 0x4?, 0x4?})
        external/gazelle~0.35.0/cmd/gazelle/gazelle.go:95 +0x1dd
main.main()
        external/gazelle~0.35.0/cmd/gazelle/gazelle.go:72 +0xf5

goroutine 10 [select]:
os/exec.(*Cmd).watchCtx(0xc0003e8b00, 0xc0001807e0)
        GOROOT/src/os/exec/exec.go:757 +0xb5
created by os/exec.(*Cmd).Start in goroutine 1
        GOROOT/src/os/exec/exec.go:743 +0x9c9

```

**Comment by Zemnmez** [comment]
Thanks! I’ll try downgradingOn 17 Jan 2024, at 11:20, Robert Collins ***@***.***> wrote:﻿
This looks like  a interaction in gazelle itself. We see this
Note that the gazelle version here is substantially newer than the default version grabbed by stackb's rules_proto.
fatal error: concurrent map read and map write

goroutine 1 [running]:
github.com/bazelbuild/bazel-gazelle/resolve.(*resolveConfig).findOverride(0xc000146db0, {{0x9e71a7?, 0x9e9411?}, {0xc000392781?, 0xb?}}, {0x9e71a7, 0x2})
        external/gazelle~0.35.0/resolve/config.go:90 +0xeb
github.com/bazelbuild/bazel-gazelle/resolve.FindRuleWithOverride(0x95a1a0?, {{0x9e71a7?, 0xc000392781?}, {0xc000392781?, 0x40?}}, {0x9e71a7, 0x2})
        external/gazelle~0.35.0/resolve/config.go:35 +0xf9
github.com/bazelbuild/bazel-gazelle/language/go.ResolveGo(0xc00045e3c0, 0x411a05?, 0xc0019e8460, {0xc000392781, 0x31}, {{0xc0004981e1, 0xe}, {0xc000482138, 0x16}, {0xc0004a2ed0, ...}, ...})
        external/gazelle~0.35.0/language/go/resolve.go:134 +0x2dd
github.com/bazelbuild/bazel-gazelle/language/go.(*goLang).Resolve.func1({0xc000392781?, 0xc001b6ed38?})
        external/gazelle~0.35.0/language/go/resolve.go:80 +0x8a
github.com/bazelbuild/bazel-gazelle/rule.(*PlatformStrings).Map.func1({0xc000475400, 0xb, 0x2?})
        external/gazelle~0.35.0/rule/platform_strings.go:147 +0xca
github.com/bazelbuild/bazel-gazelle/rule.(*PlatformStrings).MapSlice.func1(...)
        external/gazelle~0.35.0/rule/platform_strings.go:165
github.com/bazelbuild/bazel-gazelle/rule.(*PlatformStrings).MapSlice(0xc001b6f008, 0x7effd3f78108?)
        external/gazelle~0.35.0/rule/platform_strings.go:208 +0xec
github.com/bazelbuild/bazel-gazelle/rule.(*PlatformStrings).Map(0xac5680?, 0xc0003fa3f0?)
        external/gazelle~0.35.0/rule/platform_strings.go:155 +0x6f
github.com/bazelbuild/bazel-gazelle/language/go.(*goLang).Resolve(0x2ae3e90, 0xc00045e3c0, 0xc0001a81e0, 0xc0019e8460, 0xc000490b00, {0x9b00c0?, 0xc0004b3bf0?}, {{0xc0004981e1, 0xe}, {0xc000482138, ...}, ...})
        external/gazelle~0.35.0/language/go/resolve.go:79 +0x26c
main.runFixUpdate({0xc00002e05a, 0x1a}, 0x7ffca8979f71?, {0xc0001a8020, 0x3, 0x3})
        external/gazelle~0.35.0/cmd/gazelle/fix-update.go:471 +0x1bff
main.run({0xc00002e05a?, 0x1a?}, {0xc0001a8010?, 0x4?, 0x4?})
        external/gazelle~0.35.0/cmd/gazelle/gazelle.go:95 +0x1dd
main.main()
        external/gazelle~0.35.0/cmd/gazelle/gazelle.go:72 +0xf5

goroutine 10 [select]:
os/exec.(*Cmd).watchCtx(0xc0003e8b00, 0xc0001807e0)
        GOROOT/src/os/exec/exec.go:757 +0xb5
created by os/exec.(*Cmd).Start in goroutine 1
        GOROOT/src/os/exec/exec.go:743 +0x9c9

**Comment by pcj** [comment]
@vihangm https://github.com/stackb/rules_proto/releases/tag/v3.0.0
