### ISSUE TITLE
breakage when upgrading to bazel 0.22

### ISSUE THREAD

**Issue by qzmfranklin** [stackb/rules_proto#45]
I am upgrading from bazel 0.19.2 to 0.22 and encountered the following error:

```python
proto_library(
    name = 'attr_def',
    srcs = ['attr_def.proto'],
    deps = ['@com_google_protobuf//:timestamp_proto',]
)

py_proto_library(
    name = 'attr_def.pb.py',
    deps = ['attr_def'],
)
```

Building the `attr_def.pb.py` target leads to the following error snippet:
```text
in proto attribute of go_proto_library rule @io_bazel_rules_go//proto/wkt:any_go_proto: '@com_google_protobuf//:any_proto' does not have mandatory providers: 'proto'. 
```
Digging it out a bit I found that in `//:compile.bzl`, the `proto_compile.deps` attribute has a mandatory provider `proto`, as specified below:
```python
        "deps": attr.label_list(
            doc = "proto_library dependencies",
            mandatory = True,
            providers = ["proto"],
        ),
```
As I understand, the intended usage of the `deps` attribute is for collecting all the `.proto` files.

However, this design is broken by the latest changes in Bazel's `proto_library` ([here](https://docs.bazel.build/versions/master/be/protocol-buffer.html#proto_library)).

The protobuf related providers, including `proto` are moved to the `ProtoInfo` provider.

Working on a PR to fix this issue. But it is probably going to be incompatible with Bazel versions below 0.22 (or the exact commit that changed the provider structure of the native `proto_library` rule).

**Comment by pcj** [comment]
This repo has been migrated to use the newer ProtoInfo provider.  That makes the minimum compatible version 0.22.0 and has been tested on 0.25.0.
