### ISSUE TITLE
declaration of the nuget package need to be updated

### ISSUE THREAD

**Issue by nmalsang** [stackb/rules_proto#48]
The declaration of the nuget package does not respect the new format defined by the dotnet rules. 
I can provide the fix

**Comment by pcj** [comment]
Thanks @nmalsang that would be great.

**Comment by nmalsang** [comment]
The PR is coming soon

**Comment by nmalsang** [comment]
fixed 04/18/2018 
Merge pull request #70 from nmalsang/master 
issue 48 upgrade the declaration of the nuget packages
commit 8afa882b3dff5fec93b22519d34d0099083a7ce2
