### ISSUE TITLE
python_grpc_library

### ISSUE THREAD

**Issue by adibrastegarnia** [stackb/rules_proto#52]
I have a build file to generate grpc stubs for java but I am not sure what changes should I made to make it work for python. For java version, I am using: load("@io_grpc_grpc_java//:java_grpc_library.bzl", "java_grpc_library") but 

It looks like we can not pass the output of python_proto_library as a dependency to python_grpc_library correct? 

What should I expect to see in bazel-bin when I generate grpc stubs using python_grpc_library function? Here is the java version. 

https://github.com/dnosproject/dnos-core-grpc/blob/master/protobuf/proto/BUILD

Thanks,
Adib

**Comment by adibrastegarnia** [comment]
Finally I got it compiled:
https://github.com/dnosproject/dnos-core-grpc-python/blob/master/protobuf/proto/BUILD

But it gives me the following error when I try to build a binary from python file: 

```
Use --sandbox_debug to see verbose messages from the sandbox.
external/com_github_grpc_grpc/src/compiler/ruby_generator.cc: In function 'grpc::string grpc_ruby_generator::GetServices(const FileDescriptor*)':
external/com_github_grpc_grpc/src/compiler/ruby_generator.cc:165:25: error: 'const class google::protobuf::FileOptions' has no member named 'has_ruby_package'
     if (file->options().has_ruby_package()) {
                         ^
external/com_github_grpc_grpc/src/compiler/ruby_generator.cc:166:38: error: 'const class google::protobuf::FileOptions' has no member named 'ruby_package'
       package_name = file->options().ruby_package();


and here is the BUILD file:
[BUILD FILE](https://github.com/dnosproject/dnos-apps/blob/master/samplepacketprocessorpy/BUILD)
```

**Comment by adibrastegarnia** [comment]
@pcj 

Paul, it looks like you are one of the main developers of this repo. Would you please take a look at my question? Is this repo supported by bazel and grpc.io?

**Comment by pcj** [comment]
Apologies for late reply.  Can you retry this on HEAD?  grpc/grpc has been updated, it looks like an error on their end.

**Comment by seryl** [comment]
I'm seeing a similar issue; I believe it's because the python artifacts aren't isolated to their own directories like they are in java:

```bash
drwxr-xr-x   7 jtoft  wheel     224 Jun  3 03:25 storage_java_proto_grpc_pb
drwxr-xr-x   7 jtoft  wheel     224 Jun  3 03:26 storage_java_proto_lib_pb
drwxr-xr-x   7 jtoft  wheel     224 May 24 14:37 storage_java_proto_pb
```

**Note**: below are not directories

```bash
-r-xr-xr-x   1 jtoft  wheel   23559 May 24 14:37 storage_pb2.py
-r-xr-xr-x   1 jtoft  wheel    3847 May 24 14:37 storage_pb2_grpc.py
```

I'm almost positive this is why the `java_proto_library` and `java_grpc_library` don't conflict due to isolation, while the `python` equivalents do.

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
