### ISSUE TITLE
Inconsistent documentation vs implementation of transitive argument

### ISSUE THREAD

**Issue by aaliddell** [stackb/rules_proto#56]
For a number of languages, the readme states that `transitive` has a default of false: https://github.com/stackb/rules_proto/blame/master/python/README.md#L329

Whilst in the bzl file the argument is ignored and is harddoded as true: https://github.com/stackb/rules_proto/blob/f5d6eea6a4528bef3c1d3a44d486b51a214d61c2/python/python_grpc_library.bzl#L16

To correct for this, two things need doing:
- The documentation should be updated to state the default is True for affected languages
- The rules of affected languages should not use hardcoded true; the value should be pulled from kwargs with a default of true: `transitive = kwargs.get("transitive", True)`

If this sounds correct, I can send this as a PR?

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
