### ISSUE TITLE
Why `go_deps`?

### ISSUE THREAD

**Issue by dayfine** [stackb/rules_proto#58]
For the protobuf foo that depends on google.types.Any, the go_proto_library has to be generated like this:
```python
go_proto_library(
    name = "go_foo_proto",
    go_deps = [
        "@com_github_golang_protobuf//ptypes/any:go_default_library",
    ],
    deps = [":foo_proto"],
    importpath = "...",
)
```
I checked the examples for C++ / python really quickly, this (explicit dependency) is not the case for those languages. Why is this required for Go? Is there plan to remove this thing?
 As soon as I have a `bar` that depends `foo`, I have to specify the `go_deps` for `Any` again in `go_bar_proto`. It's very contagious...

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
