### ISSUE TITLE
`proto_source_root` of `proto_library` dependencies is ignored

### ISSUE THREAD

**Issue by shs96c** [stackb/rules_proto#63]
`proto_library` dependencies accept a `proto_source_root` argument, which allows protobuf definitions to be stored anywhere in the tree (there are some other attributes that can also change the behaviour).

When using `proto_compile` with protos defined this way, an error is thrown that suggests that the `proto_source_root` is being ignored.

**Comment by mikest** [comment]
I just ran into this well. We need to able to set the proto source root. The `-Ipath_to_library_pb` include the fully qualified path all the way to workspace root.

**Comment by pcj** [comment]
Related to #64, still on the TODO list.

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
