### ISSUE TITLE
proto_compile does not respect strip_import_prefix from the native proto_library

### ISSUE THREAD

**Issue by Monnoroch** [stackb/rules_proto#64]
I have a `proto_library` with a non-empty `strip_proto_prefix`. I can depend on it from other `proto_library`-ies and import proto files from it just fine. I can't do the same from `proto_compile` with this error when I'm trying to import the file:
```
Import "xxxxx.proto" was not found or had errors.
```

**Comment by Monnoroch** [comment]
Probably related to #63.

**Comment by humphrej** [comment]
If it's any help, I ran into this also and I created a minimal example:[https://github.com/humphrej/rules_proto_issue_64].

It could also be the same reason behind  #67?

**Comment by dsilvasc** [comment]
did https://github.com/stackb/rules_proto/commit/b2913e6340bcbffb46793045ecac928dcf1b34a5 fix this?

**Comment by humphrej** [comment]
I can't comment on stackb/rules_proto, but I tested strip_import_prefix behaviour in my context with rules_proto_grpc@1.0.2, bazel@2.2.0 - works well.

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
