### ISSUE TITLE
Does not work with remote action execution

### ISSUE THREAD

**Issue by Monnoroch** [stackb/rules_proto#65]
Here is my [repository](https://github.com/Monnoroch/blerpc-android/tree/bazel-1). The software is pretty complicated, but the part relevant to this example is simple. I have a `proto_library` with some protos, a `proto_plugin` with a Java binary and a `proto_compile` rule that wants to use this plugin to generate some files from the mentioned library. If one was to clone this repository, checkout to branch `bazel-1` and run `bazel test //...` with three last bazel releases it would succeed. If one was to use [remote bazel execution](https://docs.bazel.build/versions/master/remote-execution.html) and use the [standard bazelrc](https://github.com/bazelbuild/bazel-toolchains/blob/master/bazelrc/bazel-0.24.0.bazelrc) for it, when running `bazel test //... --config=remote -s` one would get the following error:

```
SUBCOMMAND: # //:test_proto_compile [action 'ProtoCompile test_proto_compile/test_proto_compile.jar']
(cd /home/monnoroch/.cache/bazel/_bazel_monnoroch/feda265a792323e37770534c35ab788f/execroot/blerpc && \
  exec env - \
  /bin/bash -c 'bazel-out/host/bin/external/com_google_protobuf/protoc --descriptor_set_out=bazel-out/k8-fastbuild/bin/test_proto_compile/descriptor.source.bin --proto_path=bazel-out/k8-fastbuild/bin/test_proto_compile --include_imports --include_source_info --java_out=bazel-out/k8-fastbuild/bin/test_proto_compile/test_proto_compile.jar --reactive-blerpc-generator_out=bazel-out/k8-fastbuild/bin/test_proto_compile --plugin=protoc-gen-reactive-blerpc-generator=bazel-out/host/bin/reactive-blerpc bazel-out/k8-fastbuild/bin/test_proto_compile/reactive-blerpc-test/src/main/proto/test_service.proto')
ERROR: /home/monnoroch/dev/blerpc-android/BUILD.bazel:74:1: error executing shell command: '/bin/bash -c bazel-out/host/bin/external/com_google_protobuf/protoc --descriptor_set_out=bazel-out/k8-fastbuild/bin/test_proto_compile/descriptor.source.bin --proto_path=bazel-out/k8-fastbuild/bin/...' failed (Exit 1)
bazel-out/host/bin/reactive-blerpc: Cannot locate runfiles directory. (Set $JAVA_RUNFILES to inhibit searching.)
--reactive-blerpc-generator_out: protoc-gen-reactive-blerpc-generator: Plugin failed with status code 1.
```

**Comment by pcj** [comment]
This repo is now on the bazelci.  The rbe is not enabled by default ATM but could be changed to make sure this is always tested.  PR welcome.

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
