### ISSUE TITLE
java_grpc_library seems does not work with protos import other protos.

### ISSUE THREAD

**Issue by zhexuany** [stackb/rules_proto#67]
Say we have:
1. foo.proto
2. bar. proto 
     import foo
3. baz.proto
    import bar

And we create proto_library for them respectively. 
I expect `java_grpc_library` works as follows:

```
java_grpc_library(
    name = "bar_grpc_library",
    deps = [
        ":foo_proto",
        ":bar_proto",
        ":baz_proto",
    ],
    verbose = 1,
)
```

but it reports some errors like "foo.proto" is not found.

**Comment by zhexuany** [comment]
@pcj If you have time, please kindly take a look at this issue. Thanks very much in advance.

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
