### ISSUE TITLE
Swift build not working with Linux + Clang8

### ISSUE THREAD

**Issue by rosun82** [stackb/rules_proto#68]
Bazel version 0.24.1

Command:

cd swift/example/swift_grpc_library
bazel test -c opt //...

Error message:

clang-8: error: unsupported option '-pass-exit-codes'

Detailed command (with -s)

/usr/bin/clang @bazel-out/host/bin/external/com_github_apple_swift_swift_protobuf/ProtoCompilerPlugin-0.params -o bazel-out/host/bin/external/com_github_apple_swift_swift_protobuf/ProtoCompilerPlugin @bazel-out/host/bin/external/com_github_apple_swift_swift_protobuf/ProtoCompilerPlugin.autolink '-fuse-ld=/usr/bin/ld' -L/usr/lib/swift/linux -Wl,-rpath,/usr/lib/swift/linux -lm -lstdc++ -lrt -ldl -static-libgcc '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -pass-exit-codes -lstdc++ -lm -Wl,--gc-sections @bazel-out/host/bin/external/com_github_apple_swift_swift_protobuf/SwiftProtobuf.autolink @bazel-out/host/bin/external/com_github_apple_swift_swift_protobuf/SwiftProtobufPluginLibrary.autolink

I tried swapping the command with gcc, but got "gcc: error: unrecognized command line option ‘-fuse-ld=/usr/bin/ld’" error, so the command above works with neither clang nor gcc.

**Comment by pcj** [comment]
Can you retry on head?  Swift rules have been updated and they build on my machine, but still fail on bazeci.  Would be interested in your observations.

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
