### ISSUE TITLE
import error with python_proto_library

### ISSUE THREAD

**Issue by manazhao** [stackb/rules_proto#72]
Basically I got the following import error when run a py_test rule which indirectly depends on python_proto_library. The code can be found at https://github.com/manazhao/py_test_fail

Command: bazel test playground/... --incompatible_disallow_dict_plus=false

=== error log ===
    from playground.lib import print_message
ImportError: No module named 'playground.lib'
===

After remove ":python_test_proto" from the dependency list of "lib", the error is gone. It seems to somehow the use of python_proto_library messes up the import path? I didn't have this issue when using the legacy "rules_protobuf". Meanwhile, I found the following issues setting up the stackb_rules,

1. need to add  --incompatible_disallow_dict_plus=false for every command. This is very inconvenient. This is probably the archive in the document is not up to date. I tried to find a newer version but just couldn't find it.
2. Following the documentation on setting up WORKSPACE file is insufficient. I also had to add "protobuf_py_deps" in the WORKSPACE file.

**Comment by pcj** [comment]
Can you retry on head?  A few big changes including --all_incompatible_changes (with noted exeception) and an aspect based implementation for python protos.

**Comment by ChrisCummins** [comment]
I also found this issue while migrating from legacy rules_pubref on de317930548a33025a3acf430bf67e21a676084f. As per @pcj's suggestion, updating to head fixed the issue. My WORKSPACE:

```
http_archive(
    name = "build_stack_rules_proto",
    sha256 = "8a9cf001e3ba5c97d45ed8eb09985f15355df4bbe2dc6dd4844cccfe71f17d3e",
    strip_prefix = "rules_proto-9e68c7eb1e36bd08e9afebc094883ebc4debdb09",
    urls = ["https://github.com/stackb/rules_proto/archive/9e68c7eb1e36bd08e9afebc094883ebc4debdb09.tar.gz"],
)
```

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
