### ISSUE TITLE
Python rules fail since 3ca0bf4

### ISSUE THREAD

**Issue by aaliddell** [stackb/rules_proto#83]
Some of the changes made in 3ca0bf4 appear to have broken the Python rules (or at least changed their behaviour significantly), for previously working rules based on the documentation. 

The main error seen is: 

```
ERROR: <snip>/BUILD:18:1: output '<snip>/blah_pb2.py' was not created
... etc for every proto file
````

Running with `verbose = 4` shows these files are created in the sandbox next to their proto file, but the expected path is missing part of the prefix. e.g consider this file tree:

```
BUILD
protos/
   something.proto
   somthing_pb2.py <- File is generated here correctly
something_pb2.py <- Expected output is here, which is incorrect
```

I'm trying to put together a smallest failing case but there seems to be a huge amount of code duplication that is making debugging difficult (compilation occurring in both compile and aspect). What is the aspect based compilation doing here compared to the compile rule? Is this not what the `transitive` argument is for?

Also, two other things to note:
- Output paths appear to no longer be prefixed by the name of the rule, meaning if multiple separate rules depend on and build the same proto file, the build will fail due to both rules touching the same file.
- The `transitive` argument is still mis-documented as being default `False` (see #56).

**Comment by pcj** [comment]
Thanks @aaliddell.  

This `aspect.bzl` indeed new...  Also yes, almost totally duplicates the `compile.bzl` but I have not had the time nor summoned the mental effort required to figure out the right abstraction that allows them to work together better.  

If you add a few lines after https://github.com/stackb/rules_proto/blob/master/aspect.bzl#L352, does it work in your case?

```python
arg = "%s/%s" % (ctx.bin_dir.path, ctx.label.workspace_root)
if ctx.label.package:
    arg += "/" + ctx.label.package
```

The transitive argument is sort-of a poor mans' substitute for an aspect.  Given that the rule ctx cannot declare files outside its package, the technique of copying over the proto files into a new tree that replicates the package structure does work, but it has negative consequences on import paths as noted in https://github.com/stackb/rules_proto/issues/47 (for example).

We can offer the old style python rules (using compile.bzl), possibly with an option to use the aspect if it's totally blocking you, otherwise hopefully not too much a stretch to get it worked out here.

**Comment by rnhaddad** [comment]
This fix seems to have fixed a similar problem for me (in case the .proto path is not "./"):
--- temp/rules_proto-4c6e7a8d519843afe2e8e95f61ad951435df5b48/aspect.bzl                2019-05-08 07:47:08.000000000 -0700
+++ rules_proto-4c6e7a8d519843afe2e8e95f61ad951435df5b48/aspect.bzl         2019-05-10 17:44:12.501966633 -0700
@@ -551,6 +551,8 @@ def _get_output_filename(src, plugin, pa
     else:
         filename = basename + pattern
+    filename = src.short_path[:-len(src.basename)]+filename
+
     return filename
 def _get_proto_filename(src):

Is this the source of the issue?

**Comment by aaliddell** [comment]
So I've tried again at the latest commit, here's what's still occurring:

- Files are still being created without a prefix of the name of the rule, meaning we're still seeing the `file 'external/com_google_protobuf/google/protobuf/timestamp_pb2.py' is generated by these conflicting actions` errors if separate multiple `*_proto_library` rules depend on a common proto file.
- What's the reason that all proto files are copied to a common tree, rather than copying only the `srcs` proto files and using `-I` to point to the `deps` files roots? `proto_library` providers appear to give sufficient information for this to work, as you get all the roots and possibly may not even need to copy the `srcs` files if you specify a different output dir.
- The timestamp file in the error above shouldn't be getting created anyway, as it's now in the transitivity block list since #55. So the transitivity rules are possibly not being applied?
- Following from the above: the timestamp proto file is coming in via `deps` not `srcs`, so shouldn't be getting built anyway, but it appears with the python aspects rule everything in both `srcs` and `deps` is now attempted to be built?

I can't currently get the original `was not created` error, but that may be because it's being masked by the `is generated by these conflicting actions` error occurring first at analysis phase.

**Comment by aaliddell** [comment]
Demo repo at https://github.com/aaliddell/rules_proto_demo
Clone and run `bazel build //...` and you will get an error along these lines:

```
ERROR: file 'demo_pb2.py' is generated by these conflicting actions:
Label: //:proto_lib_b, //:proto_lib_a
RuleClass: proto_library rule
Configuration: de2b1250788dfeca9c7ec0dbeba85f06
Mnemonic: ProtoCompile
Action key: a831069c8ff7843c7870f8b8eca9c905, 03da563bfb007c8912d4bf4274f8783a
Progress message: ProtoCompile demo_pb2.py
PrimaryInput: File:[<snip>/rules_proto_demo[source]]demo.proto
PrimaryOutput: File:[[<execution_root>]bazel-out/k8-fastbuild/bin]demo_pb2.py
Primary outputs are different: 940466972, 2097998457
Owner information: []#@build_stack_rules_proto//python:python_proto_compile.bzl%python_proto_compile_aspect[verbose_string="0"] BuildConfigurationValue.Key[de2b1250788dfeca9c7ec0dbeba85f06] //:proto_lib_b BuildConfigurationValue.Key[de2b1250788dfeca9c7ec0dbeba85f06] false {verbose_string=[0]}, []#@build_stack_rules_proto//python:python_proto_compile.bzl%python_proto_compile_aspect[verbose_string="0"] BuildConfigurationValue.Key[de2b1250788dfeca9c7ec0dbeba85f06] //:proto_lib_a BuildConfigurationValue.Key[de2b1250788dfeca9c7ec0dbeba85f06] false {verbose_string=[0]}
MandatoryInputs: Attempted action contains artifacts not in previous action (first 5):
        proto_lib_b-descriptor-set.proto.bin
Previous action contains artifacts not in attempted action (first 5):
        proto_lib_a-descriptor-set.proto.bin
Outputs: Attempted action contains artifacts not in previous action (first 5):
        demo_pb2.py
Previous action contains artifacts not in attempted action (first 5):
        demo_pb2.py
ERROR: com.google.devtools.build.lib.actions.MutableActionGraph$ActionConflictException: for demo_pb2.py, previous action: action 'ProtoCompile demo_pb2.py', attempted action: action 'ProtoCompile demo_pb2.py'
INFO: Elapsed time: 0.225s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 7 targets configured)
```

This repo tries to use the same base proto file in two different python libraries. In this case it's a bit trivial, but it's not an unreasonable situation to have different libs sharing a base proto, particularly as this error occurs when any core proto is reused (e.g. Timestamp).

Also, the Python rules docs do not specify that the pip_import rules must also be added to your WORKSPACE.

**Comment by aaliddell** [comment]
I'm currently trying to tidy the aspect and non-aspect compilations on a common base so that this can reasonably be debugged, but I am gradually coming to the conclusion that the aspect-based compilation is fundamentally an unsuitable use of aspects. Primarily, the restriction that aspects can only extract string attrs from the top level rule with values known ahead of time mean that passing the usual args (e.g. plugin options, transitivity) to the aspect implementation is near impossible (as demonstrated by the convoluted system for passing `verbose`, which is only possible because the values are known). Helpfully, this may explain why I was seeing issues with the `transitivity` attr above.

Realistically, I can't see a way forward with the aspect-based compilation at this point due to these constraints and the present problem that this issue started with :confused:. Thoughts @pcj?

I'm going to push my changes so far to my fork later today or tomorrow, which will now likely include reverting Python back to non-aspect compilation along with the other tidying I've done in the meantime. We can discuss if you want to PR/cherry-pick.

**Comment by werkt** [comment]
The aspects implementation (perhaps not strictly related to it being an aspect) of python differing so substantially from compile has led me to errors involving externally resided proto files. --proto_path not being specified at all prevents any python compilation - it refuses to even find the relatively specified proto sources. Further hilarity ensues when trying to get the python_out results to land in the expected location - required me to specify, for a non-empty workspace_root + root, a reversed --proto_path=<root>/<workspace_root> output dir. Looking forward to the revert, hoping that some of these cases can be incorporated (will put up PRs as able).

**Comment by bweston92** [comment]
any update on this?

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
