### ISSUE TITLE
Python: transitive proto dependencies are missing

### ISSUE THREAD

**Issue by aszady** [stackb/rules_proto#86]
`py_proto_library` rule seems to make available only `_pb2.py` files for protos that are target's direct dependency.
This is problematic when proto file depends on other proto, making the final _pb2 file unusable because of missing imports.

I created simple example to reproduce this problem:
https://github.com/aszady/stackb_examples/tree/master/exampleA

`bazel test //...` against quite recent version (06dd540599ac63e3f275844ecbfa2c31eec0b4d9) results in:

```
==================== Test output for //python:foo_test:
Traceback (most recent call last):
  File "(…)/foo_test.runfiles/__main__/python/foo_test.py", line 1, in <module>
    import protos.something_pb2 as something_proto
  File "(…)/foo_test.runfiles/__main__/protos/something_pb2.py", line 16, in <module>
    from protos import common_pb2 as protos_dot_common__pb2
ImportError: cannot import name 'common_pb2' from 'protos' ((…)/foo_test.runfiles/__main__/protos/__init__.py)
```

And indeed, file `common_pb2.py` is nowhere present.
```ls -R bazel-bin/python/foo_test.runfiles/__main__ -I 'pypi__*'``` says:
```
bazel-bin/python/foo_test.runfiles/__main__:
external  protos  python

bazel-bin/python/foo_test.runfiles/__main__/external:
__init__.py

bazel-bin/python/foo_test.runfiles/__main__/protos:
__init__.py  something_pb2.py

bazel-bin/python/foo_test.runfiles/__main__/python:
foo_test  foo_test.py  __init__.py
```

**Comment by pcj** [comment]
Yes that's definitely an oversight.  Can you try #89:

```python
http_archive(
    name = "build_stack_rules_proto",
    urls = ["https://github.com/stackb/rules_proto/archive/6ba87deb29137ebcb68cbb95ce6c7b215fd91802.tar.gz"],
    strip_prefix = "rules_proto-6ba87deb29137ebcb68cbb95ce6c7b215fd91802",
    sha256 = "55414c3b73c54d2d7452945db952d5ff643becd7fa21d08bea183990f59d1d2d",
)
```

**Comment by aszady** [comment]
Perfect! Using commit 6ba87deb29137ebcb68cbb95ce6c7b215fd91802 makes me and Bazel happy:
`//python:foo_test                                                        PASSED`

Thank you :)

**Comment by pcj** [comment]
Yay!  Build is green, I'll go ahead and merge it.
